/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Administrator
 */
public class form_about extends javax.swing.JFrame {

    /**
     * Creates new form form_about
     */
    private String Username;
    private int IDku;
    public form_about(String username, int IDku) {
        this.Username = username;
        this.IDku = IDku;
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tutorial_penggunaan = new javax.swing.JButton();
        ig_robit = new javax.swing.JButton();
        ig_bintang = new javax.swing.JButton();
        ig_nizar = new javax.swing.JButton();
        ig_fitri = new javax.swing.JButton();
        btn_dashboard = new javax.swing.JButton();
        btn_barang = new javax.swing.JButton();
        btn_montir = new javax.swing.JButton();
        btn_transaksi = new javax.swing.JButton();
        btn_nota = new javax.swing.JButton();
        btn_setting = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tutorial_penggunaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutorial_penggunaanActionPerformed(evt);
            }
        });
        getContentPane().add(tutorial_penggunaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1053, 150, 130, 50));
        tutorial_penggunaan.setOpaque(false);
        tutorial_penggunaan.setContentAreaFilled(false);
        tutorial_penggunaan.setBorderPainted(false);

        ig_robit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ig_robitActionPerformed(evt);
            }
        });
        getContentPane().add(ig_robit, new org.netbeans.lib.awtextra.AbsoluteConstraints(923, 220, 100, 130));
        ig_robit.setOpaque(false);
        ig_robit.setContentAreaFilled(false);
        ig_robit.setBorderPainted(false);

        ig_bintang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ig_bintangActionPerformed(evt);
            }
        });
        getContentPane().add(ig_bintang, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 333, 140, 130));
        ig_bintang.setOpaque(false);
        ig_bintang.setContentAreaFilled(false);
        ig_bintang.setBorderPainted(false);

        ig_nizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ig_nizarActionPerformed(evt);
            }
        });
        getContentPane().add(ig_nizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(733, 340, 140, 130));
        ig_nizar.setOpaque(false);
        ig_nizar.setContentAreaFilled(false);
        ig_nizar.setBorderPainted(false);

        ig_fitri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ig_fitriActionPerformed(evt);
            }
        });
        getContentPane().add(ig_fitri, new org.netbeans.lib.awtextra.AbsoluteConstraints(913, 440, 120, 150));
        ig_fitri.setOpaque(false);
        ig_fitri.setContentAreaFilled(false);
        ig_fitri.setBorderPainted(false);

        btn_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_dashboardMousePressed(evt);
            }
        });
        btn_dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dashboardActionPerformed(evt);
            }
        });
        getContentPane().add(btn_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 100, 40));
        btn_dashboard.setOpaque(false);
        btn_dashboard.setContentAreaFilled(false);
        btn_dashboard.setBorderPainted(false);

        btn_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_barangMousePressed(evt);
            }
        });
        btn_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_barangActionPerformed(evt);
            }
        });
        getContentPane().add(btn_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 100, 40));
        btn_barang.setOpaque(false);
        btn_barang.setContentAreaFilled(false);
        btn_barang.setBorderPainted(false);

        btn_montir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_montirMousePressed(evt);
            }
        });
        btn_montir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_montirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_montir, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 100, 40));
        btn_montir.setOpaque(false);
        btn_montir.setContentAreaFilled(false);
        btn_montir.setBorderPainted(false);

        btn_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_transaksiMousePressed(evt);
            }
        });
        btn_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transaksiActionPerformed(evt);
            }
        });
        getContentPane().add(btn_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 100, 40));
        btn_transaksi.setOpaque(false);
        btn_transaksi.setContentAreaFilled(false);
        btn_transaksi.setBorderPainted(false);

        btn_nota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_notaMousePressed(evt);
            }
        });
        btn_nota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_notaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_nota, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 100, 40));
        btn_nota.setOpaque(false);
        btn_nota.setContentAreaFilled(false);
        btn_nota.setBorderPainted(false);

        btn_setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_settingMousePressed(evt);
            }
        });
        btn_setting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_settingActionPerformed(evt);
            }
        });
        getContentPane().add(btn_setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 100, 40));
        btn_setting.setOpaque(false);
        btn_setting.setContentAreaFilled(false);
        btn_setting.setBorderPainted(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg_about.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ig_robitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ig_robitActionPerformed
        try {
            Desktop desktop = java.awt.Desktop.getDesktop();
            URI oURL = new URI("http://instagram.com/robit.ka");
            desktop.browse(oURL);
        } catch (URISyntaxException ex) {
            Logger.getLogger(form_about.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(form_about.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ig_robitActionPerformed

    private void ig_bintangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ig_bintangActionPerformed
        try {
            Desktop desktop = java.awt.Desktop.getDesktop();
            URI oURL = new URI("http://instagram.com/bintang_nur_pradana");
            desktop.browse(oURL);
        } catch (URISyntaxException ex) {
            Logger.getLogger(form_about.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(form_about.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ig_bintangActionPerformed

    private void ig_nizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ig_nizarActionPerformed
        try {
            Desktop desktop = java.awt.Desktop.getDesktop();
            URI oURL = new URI("http://instagram.com/nizarmurdijat_");
            desktop.browse(oURL);
        } catch (URISyntaxException ex) {
            Logger.getLogger(form_about.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(form_about.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ig_nizarActionPerformed

    private void ig_fitriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ig_fitriActionPerformed
        try {
            Desktop desktop = java.awt.Desktop.getDesktop();
            URI oURL = new URI("http://instagram.com/fsala_0023");
            desktop.browse(oURL);
        } catch (URISyntaxException ex) {
            Logger.getLogger(form_about.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(form_about.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ig_fitriActionPerformed

    private void btn_dashboardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMousePressed
        //this.setVisible(true);
        //new dashboard().setVisible(true)
    }//GEN-LAST:event_btn_dashboardMousePressed

    private void btn_barangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_barangMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_barangMousePressed

    private void btn_montirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_montirMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_montirMousePressed

    private void btn_transaksiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_transaksiMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_transaksiMousePressed

    private void btn_notaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_notaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_notaMousePressed

    private void btn_settingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_settingMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_settingMousePressed

    private void btn_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dashboardActionPerformed
        try {
            dispose();
            new dashboard(Username, IDku).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(form_about.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_dashboardActionPerformed

    private void btn_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_barangActionPerformed
        dispose();
        new form_barang(Username, IDku).setVisible(true);
    }//GEN-LAST:event_btn_barangActionPerformed

    private void btn_montirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_montirActionPerformed
        try {
            dispose();
            new form_montir(Username, IDku).setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_montirActionPerformed

    private void btn_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transaksiActionPerformed
        dispose();
        new form_transaksi(Username, IDku).setVisible(true);
    }//GEN-LAST:event_btn_transaksiActionPerformed

    private void btn_notaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_notaActionPerformed
        dispose();
        new form_nota(Username, IDku).setVisible(true);
    }//GEN-LAST:event_btn_notaActionPerformed

    private void btn_settingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_settingActionPerformed
        dispose();
        new form_settings(Username, IDku).setVisible(true);
    }//GEN-LAST:event_btn_settingActionPerformed

    private void tutorial_penggunaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutorial_penggunaanActionPerformed
        try {
            Desktop desktop = java.awt.Desktop.getDesktop();
            URI oURL = new URI("https://pdfhost.io/v/7Dz1ShMc2_MANUAL_BOOK");
            desktop.browse(oURL);
        } catch (URISyntaxException ex) {
            Logger.getLogger(form_about.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(form_about.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tutorial_penggunaanActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_barang;
    private javax.swing.JButton btn_dashboard;
    private javax.swing.JButton btn_montir;
    private javax.swing.JButton btn_nota;
    private javax.swing.JButton btn_setting;
    private javax.swing.JButton btn_transaksi;
    private javax.swing.JButton ig_bintang;
    private javax.swing.JButton ig_fitri;
    private javax.swing.JButton ig_nizar;
    private javax.swing.JButton ig_robit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton tutorial_penggunaan;
    // End of variables declaration//GEN-END:variables
}
